version: '3'
services:
  myapp:
    container_name: image-compression
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - redis
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
  redis:
    container_name: image-compression-redis
    image: redis:6.2-alpine
    restart: always